name: IE Python Checks

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/bindings/python/**'
      - 'samples/python/**'
  pull_request:
    paths:
      - 'src/bindings/python/**'
      - 'samples/python/**'
jobs:
  linters:
    runs-on: ubuntu-18.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: python -m pip install -r src/bindings/python/src/compatibility/openvino/requirements_dev.txt
      - name: Run Flake on samples
        run: python -m flake8 ./ --config=setup.cfg
        working-directory: samples/python
      - name: Create code style diff for samples
        if: failure()
        run: |
          python -m black -l 160 -S ./
          git diff > samples_diff.diff
        working-directory: samples/python
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: samples_diff
          path: samples_diff.diff
      - name: Run Flake on src
        run: python -m flake8 ./ --config=setup.cfg
        working-directory: src/bindings/python/src/compatibility/openvino
      - name: Create code style diff for Python src
        if: failure()
        run: |
          python -m black -l 160 -S ./
          git diff > src_diff.diff
        working-directory: src/bindings/python/src/compatibility/openvino
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: src_diff
          path: src_diff.diff
      - name: Run Flake on wheel
        run: python -m flake8 ./ --config=../setup.cfg
        working-directory: src/bindings/python/wheel
      - name: Create code style diff for wheel
        if: failure()
        run: |
          python -m black -l 160 -S ./
          git diff > wheel_diff.diff
        working-directory: src/bindings/python/wheel
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: wheel_diff
          path: wheel_diff.diff
      
      - name: Run MyPy
        run: python -m mypy ./ --config-file ./setup.cfg
        working-directory: src/bindings/python/src/compatibility/openvino
      - name: Run Bandit
        run: python -m bandit -r ./ -f screen
        working-directory: src/bindings/python/src/compatibility/openvino

      